FROM python:3.10-slim

WORKDIR /app

COPY report/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN pip show flask

COPY report/report.py .
COPY report/report_generator.py .
COPY report /app/report

ENV PYTHONUNBUFFERED=1
ENV FLASK_ENV=development

EXPOSE 5001

CMD ["python", "report.py"]